### PR TITLE
Feature/search form

### PR DESCRIPTION
**Pull request by SRattacasa**
- Added checkmarks for dog and cat as placeholders for future filtering options 
- Changed styling to format things into the center with justify-content
- Added a slice statement to the sorted array, so on results, only the top 3 closets groomers display
- Went through some basic troubleshooting on the sorting, added groomers.distance to the map statement so we have something to sort off of

### CODE REVIEW

**Comment by SRattacasa** [comment]
-Introduced Haversine distance function to map out distance in miles
-Resolved issues with sorting, updated the sort logic and removed outside of the map function to prevent re-renders
-Sliced the results to only show the top 2 (can adjust for future) 
-Updated reset button function to properly reset the groomers list
-Added conditional render to show distance in miles on each card
-Created logic to fill in longitude and latitude for backend users that don't have anything set 
-Removed extra comments and some additional console logs

**Comment by SRattacasa** [comment]
-Added Link from React Router DOM and then wrapped the Card styling component with Link and mapped to each ID
-Removed the API key from the front end
-Removed excess console logs used for troubleshooting

**Comment by SRattacasa** [comment]
- Added a geolocateme function that calls the browser API for location
- Integrated the new function with the updated filter function 
- Changed the input type to a clearer button 
- Allows the user to click the "Use my location" button which filters the results based on the API's reported coordinates

**Comment by SRattacasa** [comment]
- Configured pageVals as a state that uses a min and max value for use with antd Pagination
- Implemented a Pagination element from antd 
- Created a groomersPerPage variable to use for determining how many items should display per page
- Sliced the groomers array with the pageVals state elements as the sizing criteria
- Used array length for determining the total number of items in the Pagination element
- Created an onPageChange handler that is called upon page change

**Comment by SRattacasa** [comment]
- Reviewed code with Austin and Preston, merged in Austin's previous file 
- Adjusted our code to include some unique conditional rendering logic with props coming in with a "viewGroomer" prop
- Tested and verified that it worked as desired.

**Review by AustinKelsay — APPROVED** [review]

**Review by PMiddleton3 — APPROVED** [review]

**Pull request merged**
